from stanfordkarel import *
print("karel library imported successfully!")

def main():
    put_beeper()
    turn_left()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    turn_right()
    move()
    move()
    put_beeper()
    turn_right()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    turn_left()
    move()
    move()
    put_beeper()
    turn_left()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    turn_right()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()

    turn_right()
    turn_right
    pick_beeper() 
    move()
    pick_beeper() 
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    turn_left()
    move()
    move()
    pick_beeper()
    turn_left()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    turn_right()
    move()
    move()
    pick_beeper()
    turn_right()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    turn_left()
    move()
    move()
    pick_beeper()
    turn_left()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()

def turn_right():
    for i in range(3):
        turn_left()

if __name__ == '_main_':
    run_karel_program()        
       